# Generated by Django 5.0.1 on 2024-05-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0008_online_booking_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='online_booking',
            name='Booking_ID',
            field=models.IntegerField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='online_booking',
            name='Phone_Number',
            field=models.BigIntegerField(),
        ),
    ]
