# Generated by Django 5.0.1 on 2024-05-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0009_alter_online_booking_booking_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='online_booking',
            name='Booking_ID',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
    ]
