# Generated by Django 5.0.1 on 2024-05-27 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0010_alter_online_booking_booking_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='online_booking',
            old_name='Booking_ID',
            new_name='Book_ID',
        ),
    ]
