# Generated by Django 5.0.1 on 2024-05-28 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0011_rename_booking_id_online_booking_book_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='online_booking',
            name='Book_ID',
        ),
    ]
